# Generated by Django 4.0.2 on 2022-02-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='renter',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApp.renter'),
            preserve_default=False,
        ),
    ]
