# Generated by Django 4.0.2 on 2022-02-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0003_alter_rentals_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='renter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApp.renter'),
        ),
    ]
